"""
Encrypted API Keys for Firebase REST Client v3.0
=================================================

SECURITY: No plaintext API keys in source code!

Keys are pre-encrypted and stored in a separate .dat file
generated by the admin tool (01 - ADMIN).

Encryption: AES-256 with PBKDF2 (100k iterations) + HWID-bound key

Usage:
    from _encrypted_api_keys import set_runtime_keys
    set_runtime_keys()  # Call at app startup
"""

import json
from pathlib import Path

# ============================================================
# CONFIGURATION
# ============================================================

# SECURITY: Always hardware-bound, no static key mode
# USE_STATIC_KEY removed — was exploitable for key sharing

# Pre-encrypted key file (generated by admin tool or first-run setup)
# In compiled mode, __file__ may resolve differently
import sys as _sys
if getattr(_sys, 'frozen', False) or '__compiled__' in dir():
    _KEYS_FILE = Path(_sys.executable).parent / "security" / "_keys.dat"
else:
    _KEYS_FILE = Path(__file__).parent / "_keys.dat"
_KEYS_INITIALIZED = False


# ============================================================
# KEY MANAGEMENT
# ============================================================

def _get_encryption_key():
    """Get hardware-bound encryption key (always HWID-bound)."""
    try:
        from security.firebase_rest_client import _HardwareBinder
    except ImportError:
        from firebase_rest_client import _HardwareBinder
    return _HardwareBinder.get_machine_key()


def set_runtime_keys():
    """Set encrypted keys in SecureFirebaseConfig at runtime.
    
    Priority:
    1. _encrypted_keys.py (embedded in code — always available)
    2. _keys.dat (legacy external file — optional fallback)
    """
    try:
        from security.firebase_rest_client import SecureFirebaseConfig
    except ImportError:
        from firebase_rest_client import SecureFirebaseConfig
    global _KEYS_INITIALIZED

    if _KEYS_INITIALIZED:
        return True

    # Use static key mode for embedded keys (not hardware-bound)
    SecureFirebaseConfig.set_static_mode(True)

    # Priority 1: Embedded keys in _encrypted_keys.py
    try:
        from security._encrypted_keys import PRIMARY_KEY_ENCRYPTED, BACKUP_KEY_ENCRYPTED
    except ImportError:
        try:
            from _encrypted_keys import PRIMARY_KEY_ENCRYPTED, BACKUP_KEY_ENCRYPTED
        except ImportError:
            PRIMARY_KEY_ENCRYPTED = None
            BACKUP_KEY_ENCRYPTED = None
    
    if PRIMARY_KEY_ENCRYPTED and BACKUP_KEY_ENCRYPTED:
        SecureFirebaseConfig.set_encrypted_keys(PRIMARY_KEY_ENCRYPTED, BACKUP_KEY_ENCRYPTED)
        _KEYS_INITIALIZED = True
        return True

    # Priority 2: External file _keys.dat (legacy)
    if _KEYS_FILE.exists():
        try:
            SecureFirebaseConfig.set_static_mode(False)  # _keys.dat uses hardware key
            raw = _KEYS_FILE.read_bytes()
            data = json.loads(raw)
            primary_enc = data["p"].encode() if isinstance(data["p"], str) else data["p"]
            backup_enc = data["b"].encode() if isinstance(data["b"], str) else data["b"]
            SecureFirebaseConfig.set_encrypted_keys(primary_enc, backup_enc)
            _KEYS_INITIALIZED = True
            return True
        except Exception as e:
            print(f"⚠️ Failed to load _keys.dat: {e}")

    print("⚠️ No Firebase API keys available. License validation requires API keys.")
    return False


def get_key_mode():
    """Get current key mode."""
    try:
        from security.firebase_rest_client import SecureFirebaseConfig
    except ImportError:
        from firebase_rest_client import SecureFirebaseConfig
    return SecureFirebaseConfig.get_key_mode()


# set_static_mode REMOVED for security — always hardware-bound


# ============================================================
# AUTO-INITIALIZATION
# ============================================================

if __name__ != "__main__":
    try:
        set_runtime_keys()
    except Exception as e:
        print(f"Warning: Could not initialize API keys: {e}")

