"""
Integrity Check v1.1 — Startup self-hash verification.

Computes SHA-256 of critical security files and compares against
known-good hashes. Detects if files have been tampered with.

Usage:
    from security.integrity_check import verify_startup_integrity

    # At app startup:
    result = verify_startup_integrity()
    if not result['passed']:
        log.critical(f"Integrity check FAILED: {result['failures']}")
"""

import hashlib
import logging
import sys
from pathlib import Path
from typing import Dict, List

log = logging.getLogger(__name__)

# Root of the application
_APP_ROOT = Path(__file__).parent.parent


def _hash_file(filepath: Path) -> str:
    """Compute SHA-256 hash of a file."""
    try:
        h = hashlib.sha256()
        with open(filepath, 'rb') as f:
            for chunk in iter(lambda: f.read(8192), b''):
                h.update(chunk)
        return h.hexdigest()
    except (FileNotFoundError, PermissionError):
        return "MISSING"


# Critical files to verify (relative to app root)
# Hashes are populated at build time by build_release.py
CRITICAL_FILES: Dict[str, str] = {
    "security/license_client.py": "b32980f9b4dd240fb87a770a1cc6ee0a1ee24b5b90acf6ba6ef3621e8eb6663e",
    "security/firebase_rest_client.py": "da09fb94387846bcdd54642090dd6a31a722e073cbb463d3aa1cbb401f6df9c8",
    "security/trial_protection.py": "a5a0f8eee0f8aafca58dde4f663447f8af655c17a6fd6442db6c1f394b069a1c",
    "security/_encrypted_keys.py": "5f54acf0ad1c7bc70a1dcb537ca49d286200d5fa139caf42ffcc7a18b4365201",
    "security/_encrypted_api_keys.py": "09f906eb6af8355ea19f5a402abe6787d01144dbe398c65e24ca763110fc7c51",
    "services/permissions.py": "94b85392156de689d3ee2cb45a0a76a47d623a199cd23f549dbada3c8e241b54",
    "security/anti_tamper.py": "5b2ad36f6ce99d9fe10b6d32c4c07a6b3bcec7970359172eb0741f77f6fd41d8",
}

# NOTE:
# Do not self-hash this file from the inline manifest above. Any edit to the
# embedded hash values changes this file's bytes, which makes the expected hash
# self-contradictory. If self-verification is needed, the manifest must live in
# an external file signed/generated at build time.
#
# Build-time integrity hash file (generated by build_release.py)
INTEGRITY_FILE = _APP_ROOT / "build_info.json"


def verify_startup_integrity() -> dict:
    """
    Verify integrity of critical files at startup.

    Returns:
        {
            'passed': bool,
            'checked': int,
            'failures': list[str],  # filenames that failed
            'skipped': bool,        # True if no hashes configured (dev mode)
        }
    """
    result = {
        'passed': True,
        'checked': 0,
        'failures': [],
        'skipped': False,
    }

    # In development mode (no hashes configured), skip check
    if not CRITICAL_FILES:
        result['skipped'] = True
        log.debug("[Integrity] Dev mode - no hashes configured, skipping check")
        return result

    # Dev-mode detection: running from source tree (not compiled)
    # In dev mode, integrity mismatches are logged but NOT enforced
    # because source files change during development.
    _is_dev_mode = not (getattr(sys, 'frozen', False) or '__compiled__' in dir())

    for rel_path, expected_hash in CRITICAL_FILES.items():
        # Skip files with placeholder hashes (not yet regenerated by build)
        if expected_hash.startswith("PLACEHOLDER"):
            log.debug(f"[Integrity] SKIP {rel_path}: placeholder hash (rebuild needed)")
            continue

        filepath = _APP_ROOT / rel_path
        actual_hash = _hash_file(filepath)
        result['checked'] += 1

        if actual_hash != expected_hash:
            if _is_dev_mode:
                # Dev mode: log warning but don't fail (source may be edited)
                log.info(
                    f"[Integrity] DEV MISMATCH (ignored): {rel_path} "
                    f"(expected={expected_hash[:16]}..., got={actual_hash[:16]}...)"
                )
            else:
                # Production: real tamper detection
                result['passed'] = False
                result['failures'].append(rel_path)
                log.warning(
                    f"[Integrity] MISMATCH: {rel_path} "
                    f"(expected={expected_hash[:16]}..., got={actual_hash[:16]}...)"
                )

    if result['passed']:
        log.debug(f"[Integrity] All {result['checked']} files verified OK")
    else:
        log.critical(
            f"[Integrity] FAILED: {len(result['failures'])} "
            f"of {result['checked']} files tampered: {result['failures']}"
        )

    return result


def compute_all_hashes() -> Dict[str, str]:
    """
    Compute hashes of all security files.
    Used by build_release.py to populate CRITICAL_FILES dict.

    Returns:
        Dict[relative_path, sha256_hash]
    """
    security_dir = _APP_ROOT / "security"
    hashes = {}

    critical_patterns = [
        "license_client.py",
        "firebase_rest_client.py",
        "trial_protection.py",
        "_encrypted_keys.py",
        "_encrypted_api_keys.py",
        "anti_tamper.py",
    ]

    # Also hash runtime modules outside security/
    runtime_modules = [
        ("services", "permissions.py"),
    ]

    for filename in critical_patterns:
        filepath = security_dir / filename
        if filepath.exists():
            rel = f"security/{filename}"
            hashes[rel] = _hash_file(filepath)

    for subdir, filename in runtime_modules:
        filepath = _APP_ROOT / subdir / filename
        if filepath.exists():
            rel = f"{subdir}/{filename}"
            hashes[rel] = _hash_file(filepath)

    return hashes
