"""
Integrity Check v1.0 — Startup self-hash verification.

Computes SHA-256 of critical security files and compares against
known-good hashes. Detects if files have been tampered with.

Usage:
    from security.integrity_check import verify_startup_integrity

    # At app startup:
    result = verify_startup_integrity()
    if not result['passed']:
        log.critical(f"Integrity check FAILED: {result['failures']}")
"""

import hashlib
import logging
from pathlib import Path
from typing import Dict, List

log = logging.getLogger(__name__)

# Root of the application
_APP_ROOT = Path(__file__).parent.parent


def _hash_file(filepath: Path) -> str:
    """Compute SHA-256 hash of a file."""
    try:
        h = hashlib.sha256()
        with open(filepath, 'rb') as f:
            for chunk in iter(lambda: f.read(8192), b''):
                h.update(chunk)
        return h.hexdigest()
    except (FileNotFoundError, PermissionError):
        return "MISSING"


# Critical files to verify (relative to app root)
# Hashes are populated at build time by build_release.py
CRITICAL_FILES: Dict[str, str] = {
    # "security/license_client.py": "sha256_hash_here",
    # "security/firebase_rest_client.py": "sha256_hash_here",
    # "security/trial_protection.py": "sha256_hash_here",
    # "security/_encrypted_keys.py": "sha256_hash_here",
}

# Build-time integrity hash file (generated by build_release.py)
INTEGRITY_FILE = _APP_ROOT / "build_info.json"


def verify_startup_integrity() -> dict:
    """
    Verify integrity of critical files at startup.

    Returns:
        {
            'passed': bool,
            'checked': int,
            'failures': list[str],  # filenames that failed
            'skipped': bool,        # True if no hashes configured (dev mode)
        }
    """
    result = {
        'passed': True,
        'checked': 0,
        'failures': [],
        'skipped': False,
    }

    # In development mode (no hashes configured), skip check
    if not CRITICAL_FILES:
        result['skipped'] = True
        log.debug("[Integrity] Dev mode — no hashes configured, skipping check")
        return result

    for rel_path, expected_hash in CRITICAL_FILES.items():
        filepath = _APP_ROOT / rel_path
        actual_hash = _hash_file(filepath)
        result['checked'] += 1

        if actual_hash != expected_hash:
            result['passed'] = False
            result['failures'].append(rel_path)
            log.warning(
                f"[Integrity] ⚠️ MISMATCH: {rel_path} "
                f"(expected={expected_hash[:16]}..., got={actual_hash[:16]}...)"
            )

    if result['passed']:
        log.debug(f"[Integrity] ✅ All {result['checked']} files verified")
    else:
        log.critical(
            f"[Integrity] ❌ FAILED: {len(result['failures'])} "
            f"of {result['checked']} files tampered: {result['failures']}"
        )

    return result


def compute_all_hashes() -> Dict[str, str]:
    """
    Compute hashes of all security files.
    Used by build_release.py to populate CRITICAL_FILES dict.
    
    Returns:
        Dict[relative_path, sha256_hash]
    """
    security_dir = _APP_ROOT / "security"
    hashes = {}

    critical_patterns = [
        "license_client.py",
        "firebase_rest_client.py",
        "trial_protection.py",
        "_encrypted_keys.py",
        "_encrypted_api_keys.py",
        "permissions.py",
        "integrity_check.py",
    ]

    for filename in critical_patterns:
        filepath = security_dir / filename
        if filepath.exists():
            rel = f"security/{filename}"
            hashes[rel] = _hash_file(filepath)

    return hashes
