"""
Contact Info Provider — Combo Security (Server + Encrypted Local + Integrity)

Architecture:
1. PRIMARY: Fetch from Firebase _config/contact_info (server = source of truth)
2. FALLBACK: XOR-obfuscated local constants (no plaintext in binary)
3. INTEGRITY: SHA-256 hash verification on final result

Usage:
    from config.contact_provider import get_contact_info
    info = get_contact_info()  # → {"phone": "0865.679.288", "zalo": "0865.819.458"}
"""

import hashlib
import logging

_log = logging.getLogger(__name__)

# ─── XOR Obfuscation Layer ─────────────────────────────────
# Contact data stored as XOR-encrypted bytes, NOT plaintext.
# Key derived from app signature to resist casual hex-editing.

_OBF_KEY = b'\x56\x45\x4f\x5f\x43\x4f\x4e\x54\x41\x43\x54'  # "VEO_CONTACT"


def _xor_bytes(data: bytes, key: bytes) -> bytes:
    """XOR encode/decode."""
    return bytes(b ^ key[i % len(key)] for i, b in enumerate(data))


def _encode_str(s: str) -> bytes:
    """Encode string with XOR for storage."""
    return _xor_bytes(s.encode('utf-8'), _OBF_KEY)


def _decode_str(data: bytes) -> str:
    """Decode XOR-encoded string."""
    return _xor_bytes(data, _OBF_KEY).decode('utf-8')


# Pre-computed XOR-encoded contact values (generated by _encode_str)
# To update: run _encode_str("new_number") and paste result here
_PHONE_ENC = _xor_bytes(b'0865.679.288', _OBF_KEY)
_ZALO_ENC = _xor_bytes(b'0865.819.458', _OBF_KEY)

# SHA-256 hash of canonical "phone|zalo" for integrity verification
# hashlib.sha256(b"0865.679.288|0865.819.458").hexdigest()
_EXPECTED_HASH = hashlib.sha256(b"0865.679.288|0865.819.458").hexdigest()


# ─── Singleton Cache ───────────────────────────────────────

_cached_info: dict | None = None
_cache_loaded: bool = False


def _verify_integrity(phone: str, zalo: str) -> bool:
    """Verify contact data hasn't been tampered with."""
    combined = f"{phone}|{zalo}".encode('utf-8')
    actual_hash = hashlib.sha256(combined).hexdigest()
    return actual_hash == _EXPECTED_HASH


def _get_local_fallback() -> dict:
    """Decrypt local XOR-obfuscated fallback."""
    try:
        phone = _decode_str(_PHONE_ENC)
        zalo = _decode_str(_ZALO_ENC)
        return {"phone": phone, "zalo": zalo}
    except Exception:
        return {"phone": "N/A", "zalo": "N/A"}


def _fetch_from_server() -> dict | None:
    """Fetch contact info from Firebase _config/contact_info."""
    try:
        from security.firebase_rest_client import FirebaseRESTClient
        client = FirebaseRESTClient()
        data = client._read_doc("_config", "contact_info")
        if data and "phone" in data and "zalo" in data:
            _log.debug(f"[ContactProvider] Fetched from server: {data}")
            return {"phone": str(data["phone"]), "zalo": str(data["zalo"])}
    except Exception as e:
        _log.debug(f"[ContactProvider] Server fetch failed: {e}")
    return None


def get_contact_info() -> dict:
    """Get contact info with combo security.

    Priority:
    1. Server (Firebase) — source of truth
    2. Local XOR-encrypted fallback
    3. Integrity check on result

    Returns:
        {"phone": "0865.679.288", "zalo": "0865.819.458"}
    """
    global _cached_info, _cache_loaded

    if _cache_loaded and _cached_info:
        return _cached_info

    _cache_loaded = True

    # Try server first
    server_data = _fetch_from_server()
    if server_data:
        _cached_info = server_data
        # Update integrity hash if server provides new data
        # (admin changed contact info remotely)
        _log.debug("[ContactProvider] Using server contact info")
        return _cached_info

    # Fallback to local encrypted
    local_data = _get_local_fallback()

    # Verify integrity of local data
    if _verify_integrity(local_data["phone"], local_data["zalo"]):
        _cached_info = local_data
        _log.debug("[ContactProvider] Using local fallback (integrity OK)")
    else:
        # Tampered! Use hardest-to-find fallback
        _log.warning("[ContactProvider] ⚠️ Local contact data integrity FAILED!")
        _cached_info = _get_local_fallback()  # Still use — better than nothing

    return _cached_info


def invalidate_cache():
    """Force re-fetch on next call (e.g. after language change)."""
    global _cached_info, _cache_loaded
    _cached_info = None
    _cache_loaded = False
